Import( "env_etc" )

if not env_etc.no_boost_python:
  Import("env_boost_python_ext")
  env = env_boost_python_ext.Clone()
  env_etc.include_registry.prepend(
    env = env,
    paths = [ env_etc.boost_adaptbx_include ],
    )
  env.SharedLibrary(
    target="#lib/boost_adaptbx_graph_ext",
    source="graph_ext.cpp",
    )
  env.SharedLibrary(
    target="#lib/boost_adaptbx_graph_connected_component_algorithm_ext",
    source="connected_component_algorithm_ext.cpp",
    )
  #env.SharedLibrary(
  #  target="#lib/boost_adaptbx_graph_breadth_first_search_ext",
  #  source="breadth_first_search_ext.cpp",
  #  )
  env.SharedLibrary(
    target="#lib/boost_adaptbx_graph_graph_structure_comparison_ext",
    source="graph_structure_comparison_ext.cpp",
    )
