Import("env_etc", "env_scitbx_boost_python_ext")

env_scitbx_boost_python_ext.Command(
  "#libtbx/scitbx_boost/math/__init__.py",
  "#libtbx/build/SConscript", env_etc.touch_init)

pyd = env_scitbx_boost_python_ext.SharedLibrary(
  target="eigensystem_ext",
  source="eigensystem_ext.cpp",
)
env_scitbx_boost_python_ext.Install(
  "#libtbx/scitbx_boost/math", pyd)
