Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(
  target="#lib/cctbx_adptbx_ext",
  source=["adptbx_ext.cpp", "hirshfeld.cpp"])
