Import("env_base", "env_etc", "env_scitbx_boost_python")
env_base.Command(
  "__init__.py", "#/libtbx/build/SConscript", env_etc.touch_init)
env_scitbx_boost_python.SharedLibrary(target="flex", source=[
  "#/scitbx/array_family/boost_python/flex_module.cpp",
  "#/scitbx/array_family/boost_python/flex_bool.cpp",
  "#/scitbx/array_family/boost_python/flex_size_t.cpp",
  "#/scitbx/array_family/boost_python/flex_int.cpp",
  "#/scitbx/array_family/boost_python/flex_long.cpp",
  "#/scitbx/array_family/boost_python/flex_float.cpp",
  "#/scitbx/array_family/boost_python/flex_double.cpp",
  "#/scitbx/array_family/boost_python/flex_complex_double.cpp",
  "#/scitbx/array_family/boost_python/flex_std_string.cpp",
])
