Import("env_base", "env_etc")

env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
)
env_etc.include_registry.append(
  env=env,
  paths=env_etc.iotbx_common_includes)
env.Program(target="tst_parsers",
            source="tst_parsers.cpp")
