Import("env_iotbx_boost_python_ext", "env_etc", "env_base")
env = env_iotbx_boost_python_ext.Clone()
env_etc.include_registry.append(env=env, paths=[env_etc.fable_include])
env.SharedLibrary(target="#lib/iotbx_shelx_ext", source=[
  "shelx_ext.cpp",
])

env_program = env_base.Clone()
env_etc.include_registry.append(env=env_program,
                                paths=["."] 
                              + env_etc.iotbx_common_includes
                              + [env_etc.fable_include])
if (env_etc.static_libraries): builder = env_program.StaticLibrary
else:                          builder = env_program.SharedLibrary
env_program.Program(target="tests/tst_hklf",
                    source="tst_hklf.cpp")
