import libtbx.load_env
import os
Import("env_base", "env_etc")

env = env_base.Clone(SHLINKFLAGS=env_etc.shlinkflags)
env.Append(LIBS=["cctbx"] + env_etc.libm)
env_etc.include_registry.append(
  env=env,
  paths=env_etc.prime_common_includes)
if (env_etc.static_libraries): builder = env.StaticLibrary
else:                          builder = env.SharedLibrary

if (not env_etc.no_boost_python):
  Import("env_boost_python_ext")
  env_local_ext = env_boost_python_ext.Clone()
  env_local_ext.Prepend(
      LIBS=["cctbx", "scitbx_boost_python"])
  env_local_ext.SharedLibrary(
      target="#lib/prime_index_ambiguity_ext", source="ext.cpp")

  env_etc.include_registry.append(
    env=env_local_ext,
    paths=env_etc.prime_common_includes)
