import os

Import("env_etc")

if (not env_etc.no_boost_python) :
  Import("env_iotbx_boost_python_ext")
  env = env_iotbx_boost_python_ext.Clone()
  env.Prepend(LIBS=["cctbx"])
  if (os.name == "nt") :
    env.Prepend(LIBS=["Advapi32"])
  env_etc.enable_more_warnings(env=env)
  env.SharedLibrary(
    target="#lib/iotbx_dsn6_map_ext",
    source=["ext.cpp"])
