Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#lib/cctbx_sgtbx_ext", source=[
  "sgtbx_ext.cpp",
  "brick.cpp",
  "change_of_basis.cpp",
  "find_affine.cpp",
  "lattice_symmetry.cpp",
  "phase_info.cpp",
  "reciprocal_space_asu.cpp",
  "rot_mx.cpp",
  "rt_mx.cpp",
  "search_symmetry.cpp",
  "seminvariant.cpp",
  "site_symmetry.cpp",
  "space_group.cpp",
  "space_group_type.cpp",
  "sym_equiv_sites.cpp",
  "symbols.cpp",
  "tensor_rank_2.cpp",
  "tensors.cpp",
  "tr_vec.cpp",
  "wyckoff.cpp",
  "select_generators.cpp"
])
