Import("env_cctbx_boost_python_ext", "env_etc")
env_bpl = env_cctbx_boost_python_ext.Clone()
env_etc.enable_more_warnings(env=env_bpl)
env_bpl.Prepend(LIBS=["cctbx"])
env_bpl.SharedLibrary(
  target="#lib/cctbx_geometry_restraints_ext",
  source=[
    "geometry_restraints_ext.cpp",
    "bond_bpl.cpp",
    "bond_similarity_bpl.cpp",
    "bond_sorted_bpl.cpp",
    "nonbonded_bpl.cpp",
    "nonbonded_sorted_bpl.cpp",
    "angle_bpl.cpp",
    "dihedral_bpl.cpp",
    "chirality_bpl.cpp",
    "planarity_bpl.cpp",
    "parallelity_bpl.cpp",
    "motif_bpl.cpp"])
