Import("env_base", "env_etc")
env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
)
env_etc.include_registry.append(
  env=env,
  paths=["."] + env_etc.scitbx_common_includes)
envlm = env.Copy(
  LIBS=env_etc.libm
)
env.Program(target="tst_householder",
            source="tst_householder.cpp")
env.Program(target="tst_svd",
            source="tst_svd.cpp")
env.Program(target="tst_givens",
            source="tst_givens.cpp")
