Import("env_base", "env_etc")
env = env_base.Clone()
# TODO env_etc.enable_more_warnings(env=env)
env_etc.include_registry.append(
  env=env,
  paths=["."] + env_etc.scitbx_common_includes)
env_etc.enable_fast_linalg(env)
env.Program(target="tst_householder",
            source="tst_householder.cpp")
env.Program(target="tst_svd",
            source="tst_svd.cpp")
env.Program(target="tst_cholesky",
            source="tst_cholesky.cpp")
env.Program(target="tst_givens",
            source="tst_givens.cpp")
