# suitename

ifeq ($(MAKECMDGOALS),debug)
	CFLAGS = -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -arch x86_64
else
	CFLAGS = -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -arch x86_64
endif

LIBS = -lm -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -arch x86_64

# ---------------------------------------------------------------------
PROG_FLGS   =  
OBJS = suitename.o suitenscrt.o suiteninit.o suiteninpt.o \
       suitenout.o suitenutil.o

# ---------------------------------------------------------------------
HEADERS = suitename.h suitenscrt.h suitenutil.h suiteninit.h suiteninpt.h \
          suitenout.h

suitename: $(OBJS)
	cc -o suitename $(CFLAGS) $(OBJS) $(LIBS)

debug:     $(OBJS)
	cc -o suitename $(CFLAGS) $(OBJS) $(LIBS)

clean:
	rm -f *.o
# ------------------------------------------------------------------------
# Dependencies  (presume .o<-.c by standard cc compiler)

suitename.o:  $(HEADERS)
suiteninit.o: $(HEADERS)
suitenscrt.o: $(HEADERS)
suiteninpt.o: $(HEADERS)
suitenout.o:  $(HEADERS)
suitenutil.o: $(HEADERS)

