Import("env_base", "env_etc")
env = env_base.Clone()
env_etc.enable_more_warnings(env=env)
env_etc.include_registry.append(
  env=env,
  paths=env_etc.scitbx_common_includes)
envlm = env.Clone(LIBS=['boost_timer', 'boost_chrono', env_etc.libm])
for i in [1,2,3]:
  envlm.Program(target="driver%d"%i, source="driver%d.cpp"%i)
