Import("env_base", "env_etc")
env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
)
env_etc.include_registry.append(
  env=env,
  paths=env_etc.scitbx_common_includes)
envlm = env.Copy(LIBS=env_etc.libm)
for i in [1,2,3]:
  envlm.Program(target="driver%d"%i, source="driver%d.cpp"%i)
