Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#lib/cctbx_dmtbx_ext", source=[
  "dmtbx_ext.cpp",
  "triplet_phase_relation.cpp",
  "triplet_generator.cpp",
])
