import os
Import("env_etc")

if (not env_etc.no_boost_python):
  Import("env_iotbx_boost_python_ext")
  env = env_iotbx_boost_python_ext.Clone()
  env.Prepend(LIBS=["cctbx", "scitbx_boost_python"])
  env_etc.enable_more_warnings(env=env)
  env.SharedLibrary(
    target="#lib/mmtbx_secondary_structure_ext",
    source=["ext.cpp"])
  env.Prepend(LIBS=["iotbx_pdb"])
  env.SharedLibrary(
    target="#lib/mmtbx_dssp_ext",
    source=["dssp_ext.cpp"])
