Import("env_antlr3_iotbx_boost_python_ext", "env_etc")
env = env_antlr3_iotbx_boost_python_ext.Clone()

env.SharedLibrary(target="#lib/iotbx_cif_ext", source=[
  "cif_ext.cpp",
  "../cifParser.cpp",
  "../cifLexer.cpp",
])
