Import("env_base", "env_etc")
env = env_base.Clone()
env_etc.include_registry.append(
  env=env,
  paths=["."] + env_etc.scitbx_common_includes)
env.Program(target="tst", source="tst.cpp")

Import("env_scitbx_boost_python_ext")
env_scitbx_boost_python_ext.SharedLibrary(
  target="#lib/scitbx_optional_copy_ext",
  source=["ext.cpp"])
