Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx", "omptbx"])
env.SharedLibrary(target="#lib/cctbx_maptbx_ext", source=[
  "maptbx_ext.cpp",
  "grid_indices_around_sites.cpp",
  "grid_tags.cpp",
  "gridding.cpp",
  "misc.cpp",
  "peak_search.cpp",
  "pymol_interface.cpp",
  "statistics.cpp",
  "structure_factors.cpp",
  "coordinate_transformers.cpp",
])
