Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#lib/cctbx_maptbx_ext", source=[
  "maptbx_ext.cpp",
  "grid_tags.cpp",
  "gridding.cpp",
  "misc.cpp",
  "peak_search.cpp",
  "pymol_interface.cpp",
  "statistics.cpp",
  "structure_factors.cpp",
  "real_space_refinement.cpp",
])
