Import("env_scitbx_boost_python")
lbfgs_pyd = env_scitbx_boost_python.SharedLibrary(target="lbfgs", source=[
  "lbfgs_module.cpp",
])
env_scitbx_boost_python.Install("#/libtbx/scitbx_boost", lbfgs_pyd)
