Import("env_scitbx_boost_python_ext")
lbfgs_pyd = env_scitbx_boost_python_ext.SharedLibrary(target="lbfgs", source=[
  "lbfgs_module.cpp",
])
env_scitbx_boost_python_ext.Install("#/libtbx/scitbx_boost", lbfgs_pyd)
