Import("env_scitbx_boost_python_ext", "env_etc")
env = env_scitbx_boost_python_ext.Clone()
# TODO env_etc.enable_more_warnings(env=env)
env.SharedLibrary(
  target="#lib/scitbx_sparse_ext",
  source=[
    "vector.cpp",
    "matrix.cpp",
    "approx_equal.cpp",
    "random.cpp",
    "lu_factorization.cpp",
    "sparse_ext.cpp",
])
