Import("env_etc")
if (not env_etc.no_boost_python):
  Import("env_boost_python_ext")
  env = env_boost_python_ext.Clone()
  env_etc.include_registry.append(
    env=env,
    paths=[
      env_etc.libtbx_include,
      env_etc.scitbx_include])
  env.SharedLibrary(
    target="#lib/ipctbx_ext",
    source="ext.cpp")
