Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#lib/cctbx_emma_ext", source=[
  "emma_ext.cpp",
])
env.SharedLibrary(target="#lib/cctbx_orientation_ext", source=[
  "orientation_ext.cpp",
])
