Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
pyd = env.SharedLibrary(target="emma_ext", source=[
  "emma_ext.cpp",
])
env.Install("#libtbx/cctbx_boost", pyd)
