Import("env_base", "env_etc")
env = env_base.Clone(
  CXXFLAGS=env_etc.cxxflags_base,
)
env.Prepend(LIBS=["cctbx"])
env.Append(LIBS='boost_timer')
env.Append(LIBS=env_etc.libm)
env_etc.include_registry.append(
  env=env,
  paths=env_etc.cctbx_common_includes)
env.Program(
  target="time_trigonometry",
  source=["time_trigonometry.cpp"])
