from  cctbx.arraytbx import shared_storage
store = shared_storage.int(5)
store.fill(1)
print store.as_tuple()
store = shared_storage.float(5)
store.fill(2)
print store.as_tuple()
store = shared_storage.double(5)
store.fill(3)
print store.as_tuple()
store = shared_storage.complex(5)
store.fill(4+5j)
print store.as_tuple()
a = shared_storage.int(5)
a.fill(6)
b = shared_storage.int(a.handle(), 4)
print a.as_tuple()
print b.as_tuple()
a[2] = 33
print a.as_tuple()
print b.as_tuple()
a = shared_storage.int_3d((2,3,4))
a.fill(1)
print a.size()
print a.dim()
print a.as_tuple()
b = shared_storage.int(a.handle(), 4)
b.fill(2)
c = a.as_1d()
print c.as_tuple()
