Import("env_base", "env_etc")
env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
)
env.Append(LIBPATH=["#lib"])
env.Prepend(LIBS=["cctbx"])
env.Append(LIBS=env_etc.libm)
env_etc.include_registry.append(
  env=env,
  paths=["."] + env_etc.cctbx_common_includes)
for target in ["getting_started",
               "convert_ccp4_symop_lib",
               "lattice_symmetry"]:
  exe = env.Program(target=target, source=target+".cpp")
  env_etc.libtbx_env.create_dispatcher_in_bin(
    source_file=exe[0].get_abspath(),
    target_file="cctbx."+target)
