Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#libtbx/cctbx_crystal_ext", source=[
  "crystal_ext.cpp",
  "close_packing_bpl.cpp",
  "direct_space_asu_bpl.cpp",
  "neighbors_bpl.cpp",
  "pair_tables_bpl.cpp",
  "symmetry_bpl.cpp",
])
