Import("env_cctbx_boost_python_ext")

env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
for module in ("chemical_elements", "henke", "fp_fdp", "icsd_radii", "neutron",
               "sasaki", "tiny_pse", "wavelengths", "xray_scattering",
               "covalent_radii", "attenuation_coefficient"):
  env.SharedLibrary(
    target="#lib/cctbx_eltbx_"+module+"_ext",
    source=[module+"_ext.cpp"])
