Import("env_etc", "env_cctbx_boost_python_ext")

env_cctbx_boost_python_ext.Command(
  "#libtbx/cctbx_boost/eltbx/__init__.py",
  "#libtbx/libtbx/touch_init.py", env_etc.touch_init)

env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
for module in ("henke", "fp_fdp", "icsd_radii", "neutron",
               "sasaki", "tiny_pse", "wavelengths", "xray_scattering"):
  env.SharedLibrary(
    target="#libtbx/cctbx_boost/eltbx/"+module+"_ext",
    source=[module+"_ext.cpp"])
