Import("env_base", "env_etc")
env_base.Command(
  "__init__.py", "#/libtbx/build/SConscript", env_etc.touch_init)
env_scitbx_boost_python = env_base.Copy(
  CPPPATH=[env_etc.scitbx_include,
           env_etc.boost_include,
           env_etc.python_include],
  CXXFLAGS=env_etc.cxxflags_base,
  SHCXXFLAGS=env_etc.cxxflags_base,
  SHLINKFLAGS=env_etc.shlinkflags_bpl,
  SHLIBPREFIX="",
  LIBPATH=["#/libtbx"] + env_etc.libpath_python,
  LIBS=["scitbx_boost_python", "bpl"] + env_etc.libs_python + env_etc.libm,
)
env_scitbx_boost_python.Append(SHCXXFLAGS=env_etc.cxxflags_bpl_defines_base)
env_scitbx_boost_python.Replace(SHLIBSUFFIX=env_etc.extension_module_suffix)
Export("env_scitbx_boost_python")
env_scitbx_boost_python.SharedLibrary(target="lbfgs", source=[
  "#/scitbx/lbfgs/boost_python/lbfgs_module.cpp",
])
SConscript("array_family/SConscript")
