Import("env_scitbx_boost_python_ext")
pyd = env_scitbx_boost_python_ext.SharedLibrary(
  target="fftpack_ext",
  source=["fftpack_module.cpp"])
env_scitbx_boost_python_ext.Install("#libtbx/scitbx_boost", pyd)
