Import("env_scitbx_boost_python_ext", "env_etc")

env = env_scitbx_boost_python_ext.Clone()
env_etc.enable_more_warnings(env=env)
env.SharedLibrary(
  target="#lib/scitbx_wigner_ext",
  source=[
    "ext.cpp"])
