Import("env_smtbx_boost_python_ext")
env = env_smtbx_boost_python_ext.Clone()
env.Prepend(LIBS=["smtbx_refinement_constraints", "scitbx_boost_python"])
env.SharedLibrary(target="#lib/smtbx_refinement_least_squares_ext", source=[
  "least_squares_ext.cpp",
  "weighting_schemes.cpp",
  "least_squares.cpp",
])
