Import("env_cctbx_boost_python_ext")
env_bpl = env_cctbx_boost_python_ext.Copy()
env_bpl.Prepend(LIBS=["cctbx"])
env_bpl.SharedLibrary(
  target="#libtbx/cctbx_geometry_restraints_ext",
  source=[
    "geometry_restraints_ext.cpp",
    "bond_bpl.cpp",
    "nonbonded_bpl.cpp",
    "pair_proxies_bpl.cpp",
    "angle_bpl.cpp",
    "dihedral_bpl.cpp",
    "chirality_bpl.cpp",
    "planarity_bpl.cpp"])
