Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#lib/cctbx_mintbx_ext", source=[
  "mintbx_ext.cpp",
  "k_b_scaling.cpp",
])
