Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
pyd = env.SharedLibrary(target="mintbx_ext", source=[
  "mintbx_ext.cpp",
  "k_b_scaling.cpp",
])
env.Install("#libtbx/cctbx_boost", pyd)
