import libtbx.config
from libtbx.path import norm_join
from libtbx.touch_init import touch_init
import sys, os

class empty: pass

def set_python_include_and_libs(env_etc):
  env_etc.python_include = libtbx.config.python_include_path()
  if (sys.platform == "win32"):
    env_etc.libs_python = ["python" + sys.version[0] + sys.version[2]]
    env_etc.libpath_python = [sys.prefix + r"\libs"]
  elif (env_etc.compiler == "tru64_cxx"):
    env_etc.libs_python = ["pthread",]
    env_etc.libpath_python = []
  else:
    env_etc.libs_python = []
    env_etc.libpath_python = []
  if (env_etc.compiler == "darwin_g++"):
    env_etc.python_framework = "/".join(
      env_etc.python_include.split("/")[:-2] + ["Python"])

env_etc = empty()
env_etc.libtbx_env = libtbx.config.env()
env_etc.libtbx_env.write_api_file()
env_etc.compiler = ARGUMENTS.get("compiler", 0)
env_etc.no_boost_python = ARGUMENTS.get("no_boost_python", 0)
env_etc.touch_init = touch_init
env_etc.norm_join = norm_join

if (env_etc.compiler == 0):
  if (sys.platform == "win32"):
    env_etc.compiler = "win32_cl"
  elif (sys.platform.startswith("linux")):
    env_etc.compiler = "unix_gcc"
  elif (sys.platform.startswith("osf")):
    env_etc.compiler = "tru64_cxx"
  elif (sys.platform.startswith("irix")):
    env_etc.compiler = "irix_CC"
  elif (sys.platform.startswith("darwin")):
    env_etc.compiler = "darwin_g++"
assert env_etc.compiler in (
  "win32_cl",
  "unix_gcc",
  "unix_ecc",
  "unix_icc",
  "tru64_cxx",
  "irix_CC",
  "darwin_g++",
)

if (sys.platform == "win32"):
  env_etc.static_libraries = 1
  env_etc.static_bpl = 0
  env_base = Environment(ENV=os.environ)
  set_python_include_and_libs(env_etc)
  env_etc.extension_module_suffix = ".pyd"
  if (env_etc.compiler == "win32_cl"):
    env_base.Replace(
      SHCC="cl",
      SHCXX="cl",
      SHLINK="link",
    )
    env_etc.cxxflags_base = Split("""
        /nologo
        /MD
        /GR /GX
        /Zm800
    """)
    env_etc.ccflags_base = Split("""
        /nologo
        /MD
        /Zm800
    """)
    if (libtbx.config.build_options.optimization):
      opts = ["/DNDEBUG", "/Ox"]
    else:
      opts = ["/Od"]
    if (libtbx.config.build_options.debug_symbols):
      raise RuntimeError, "Debug build not supported."
    env_etc.cxxflags_base.extend(opts)
    env_etc.ccflags_base.extend(opts)
    env_etc.shlinkflags = "/nologo /incremental:no /dll"
    env_etc.shlinkflags_bpl = env_etc.shlinkflags
    env_etc.libm = []
  else:
    raise "Unknown compiler choice:", env_etc.compiler
else:
  env_base = Environment(
    ENV=os.environ,
    tools=['gcc','g++','gnulink','ar'])
  set_python_include_and_libs(env_etc)
  env_etc.extension_module_suffix = ".so"
  env_etc.libm = ["m"]
  if (env_etc.compiler == "tru64_cxx"):
    env_etc.static_libraries = 0
    env_etc.static_bpl = 0
    cxx = "cxx"#-model ansi"
    env_base.Replace(
      CC="cc",
      SHCC="cc",
      CXX=cxx,
      LINK=cxx,
      SHCXX=cxx,
      SHLINK=cxx,
    )
    env_etc.cxxflags_base = Split("""
        -std strict_ansi
        -msg_display_number -msg_disable 186,450,1115
        -tlocal
    """)
    env_etc.ccflags_base = Split("""
        -std1
    """)
    if (libtbx.config.build_options.optimization):
      opts = ["-DNDEBUG", "-O2"]
    else:
      opts = ["-O0"]
    if (libtbx.config.build_options.debug_symbols):
      opts.insert(0, "-g")
    env_etc.cxxflags_base.extend(opts)
    env_etc.ccflags_base.extend(opts)
    env_etc.shlinkflags = "-shared -expect_unresolved 'Py*'" \
                        + " -expect_unresolved '_Py*'"
    env_etc.shlinkflags_bpl = env_etc.shlinkflags
  elif (env_etc.compiler == "unix_gcc"):
    env_etc.static_libraries = 0
    env_etc.static_bpl = 0
    env_base.Replace(
      CC="gcc",
      SHCC="gcc",
      CXX="g++",
      LINK="g++",
      SHCXX="g++",
      SHLINK="g++",
    )
    env_etc.cxxflags_base = Split("""
      -fPIC
      -ftemplate-depth-120
      -w
    """)
    env_etc.ccflags_base = Split("""
      -w
    """)
    if (libtbx.config.build_options.optimization):
      opts = ["-DNDEBUG", "-O3"]
    else:
      opts = ["-O0", "-fno-inline"]
    if (libtbx.config.build_options.debug_symbols):
      opts.insert(0, "-g")
    env_etc.cxxflags_base.extend(opts)
    env_etc.ccflags_base.extend(opts)
    env_etc.shlinkflags = "-shared"
    env_etc.shlinkflags_bpl = env_etc.shlinkflags
  elif (env_etc.compiler == "unix_ecc"):
    env_etc.static_libraries = 0
    env_etc.static_bpl = 0
    env_base.Replace(
      CC="ecc",
      SHCC="ecc",
      CXX="ecc",
      LINK="ecc",
      SHCXX="ecc",
      SHLINK="ecc",
    )
    env_etc.cxxflags_base = Split("""
      -fPIC
    """)
    env_etc.ccflags_base = Split("""
    """)
    if (libtbx.config.build_options.optimization):
      opts = ["-DNDEBUG", "-O", "-tpp2", "-ip", "-ftz"]
    else:
      opts = ["-O0"]
    if (libtbx.config.build_options.debug_symbols):
      opts.insert(0, "-g")
    env_etc.cxxflags_base.extend(opts)
    env_etc.ccflags_base.extend(opts)
    env_etc.shlinkflags = "-shared"
    env_etc.shlinkflags_bpl = env_etc.shlinkflags
  elif (env_etc.compiler == "unix_icc"):
    env_etc.static_libraries = 0
    env_etc.static_bpl = 0
    env_base.Replace(
      CC="icc",
      SHCC="icc",
      CXX="icc",
      LINK="icc",
      SHCXX="icc",
      SHLINK="icc",
    )
    env_etc.cxxflags_base = Split("""
      -fPIC
    """)
    env_etc.ccflags_base = Split("""
    """)
    if (libtbx.config.build_options.optimization):
      opts = ["-DNDEBUG", "-O2"]
    else:
      opts = ["-O0"]
    if (libtbx.config.build_options.debug_symbols):
      opts.insert(0, "-g")
    env_etc.cxxflags_base.extend(opts)
    env_etc.ccflags_base.extend(opts)
    env_etc.shlinkflags = "-shared"
    env_etc.shlinkflags_bpl = env_etc.shlinkflags
  elif (env_etc.compiler == "irix_CC"):
    env_etc.static_libraries = 0
    env_etc.static_bpl = 0
    cxx = "CC -n32 -mips4 -LANG:std"
    cxx += " -LANG:pch=OFF -no_prelink -ptused" \
         + " -FE:template_in_elf_section" \
         + " -FE:eliminate_duplicate_inline_copies"
    env_base.Replace(
      CC="cc",
      SHCC="cc",
      CXX=cxx,
      LINK=cxx+" -LD_MSG:off=15,84",
      SHCXX=cxx,
      SHLINK=cxx,
    )
    env_etc.cxxflags_base = ["-woff", "1001,1188,1234,1311,1682,3439"]
    if (env_etc.libtbx_env.has_dist("boost")):
      env_etc.cxxflags_base.insert(0,
        "-I%s/boost/compatibility/cpp_c_headers"
        % env_etc.libtbx_env.dist_path("boost"))
    env_etc.ccflags_base = []
    if (libtbx.config.build_options.optimization):
      opts = ["-DNDEBUG", "-O2", "-OPT:Olimit=0"]
    else:
      opts = ["-O0"]
    if (libtbx.config.build_options.debug_symbols):
      opts.insert(0, "-g")
    env_etc.cxxflags_base.extend(opts)
    env_etc.ccflags_base.extend(opts)
    env_etc.shlinkflags = ["-shared", "-LD_MSG:off=15,84"]
    env_etc.shlinkflags_bpl = env_etc.shlinkflags
  elif (env_etc.compiler == "darwin_g++"):
    env_etc.static_libraries = 1
    env_etc.static_bpl = 0
    env_base.Replace(
      CC="gcc",
      SHCC="gcc",
      CXX="g++",
      LINK="g++",
      SHCXX="g++",
      SHLINK="g++",
      SHLIBSUFFIX=".dylib",
    )
    env_base.Append(LIBSUFFIXES=[".dylib"])
    env_etc.cxxflags_base = Split("""
      -fPIC
      -ftemplate-depth-120
      -w
    """)
    env_etc.ccflags_base = Split("""
      -w
    """)
    if (libtbx.config.build_options.optimization):
      opts = ["-DNDEBUG", "-O3"]
    else:
      opts = ["-O0", "-fno-inline"]
    if (libtbx.config.build_options.debug_symbols):
      opts.insert(0, "-g")
    env_etc.cxxflags_base.extend(opts)
    env_etc.ccflags_base.extend(opts)
    env_etc.shlinkflags = []
    env_etc.shlinkflags_bpl = [
      "-w", # for some odd reason -bundle cannot be the first option
      "-bundle",
      "-bundle_loader", env_etc.python_framework, env_etc.python_framework,]
  else:
    raise "Unknown compiler choice:", env_etc.compiler

env_etc.libtbx_build = env_etc.libtbx_env.LIBTBX_BUILD
env_etc.libtbx_include = norm_join(env_etc.libtbx_build, "libtbx/include")
env_etc.libtbx_lib = norm_join(env_etc.libtbx_build, "libtbx")

try:
  CScanRegisterFlags(python=env_etc.python_include)
except:
  pass

Export("env_base", "env_etc")
