Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#libtbx/cctbx_boost/xray_ext", source=[
  "xray_ext.cpp",
  "conversions.cpp",
  "gradient_flags.cpp",
  "gradients_direct.cpp",
  "fast_gradients.cpp",
  "scatterer.cpp",
  "sampling_base.cpp",
  "sampled_model_density.cpp",
  "structure_factors_direct.cpp",
  "structure_factors_simple.cpp",
  "targets.cpp",
])
