import libtbx.load_env
Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()

libs = ["cctbx"]
sources = [
  "xray_ext.cpp",
  "conversions.cpp",
  "gradient_flags.cpp",
  "gradients_direct.cpp",
  "fast_gradients.cpp",
  "minimization.cpp",
  "scatterer_flags.cpp",
  "scatterer.cpp",
  "scattering_type_registry.cpp",
  "sampling_base.cpp",
  "sampled_model_density.cpp",
  "structure_factors_direct.cpp",
  "structure_factors_simple.cpp",
  "targets.cpp",
  "f_model_bpl.cpp",
  "twin_targets.cpp",
]

multithreaded_sources = [
  "structure_factors_direct_multithread.cpp",
]

if libtbx.env.build_options.enable_boost_threads:
  libs.append("boost_thread")
  sources.extend(multithreaded_sources)
env.Prepend(LIBS=libs)
env.SharedLibrary(target="#lib/cctbx_xray_ext", source=sources)
