Import("env_iotbx_boost_python_ext")
env = env_iotbx_boost_python_ext.Clone()

env.SharedLibrary(target="#lib/iotbx_detectors_ext", source=[
  "detectors_ext.cpp","image_divider.cpp"
])

env.SharedLibrary(target="#lib/iotbx_detectors_bruker_ext", source=[
  "bruker_ext.cpp","bruker.cpp",
])
