Import("env_base", "env_etc")
env = env_base.Clone(
  CXXFLAGS=env_etc.cxxflags_base,
)
env_etc.include_registry.append(
  env=env,
  paths=["."] + env_etc.scitbx_common_includes)
envlm = env.Clone(
  LIBS=env_etc.libm
)
env.Program(target="tst",
            source="tst.cpp")
