Import("env_cctbx_boost_python_ext")
env_bpl = env_cctbx_boost_python_ext.Copy()
env_bpl.Prepend(LIBS=["cctbx"])
env_bpl.SharedLibrary(
  target="#libtbx/cctbx_adp_restraints_ext",
  source=[
    "adp_restraints_ext.cpp"])
