Import("env_smtbx_boost_python_ext")
env = env_smtbx_boost_python_ext.Copy()
env.SharedLibrary(target="#lib/smtbx_array_family_ext",
                  source=[ "af_ext.cpp",
                         ])
