Import("env_base", "env_etc")

env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
)
env_etc.include_registry.append(
  env=env,
  paths=env_etc.scitbx_common_includes)
envlm = env.Copy(
  LIBS=env_etc.libm
)
envlm.Program(target="tst_numeric_parsers",
              source="tst_numeric_parsers.cpp")
envlm.Program(target="tst_numeric_manipulators",
              source="tst_numeric_manipulators.cpp")
