Import("env_iotbx_boost_python_ext")
env = env_iotbx_boost_python_ext.Copy()
env.Prepend(LIBS=["iotbx","cmtz","cctbx"])
if (env["SHCXX"] == "libtbx.mac_os_x_cpp"):
  env.Replace(SHCXX="g++")
env.SharedLibrary(
  target="#libtbx/iotbx_boost/mtz",
  source=["cppmtzmodule.cpp"])
