Import("env_iotbx_boost_python_ext")
env = env_iotbx_boost_python_ext.Copy()
env.Prepend(LIBS=["iotbx","cmtz","cctbx"])
env.SharedLibrary(
  target="#libtbx/iotbx_mtz_ext",
  source=["cppmtzmodule.cpp", "writer.cpp"])
