Import("env_iotbx_boost_python_ext")
env = env_iotbx_boost_python_ext.Copy()
env.Prepend(LIBS=["iotbx","cmtz",])
pyd = env.SharedLibrary(target="mtz", source=[
  "cppmtzmodule.cpp",
])
env.Install("#libtbx/iotbx_boost", pyd)
