import sys

def write_copyright():
  print \
"""/* Copyright (c) 2001 The Regents of the University of California through
   E.O. Lawrence Berkeley National Laboratory, subject to approval by the
   U.S. Department of Energy. See files COPYRIGHT.txt and
   cctbx/LICENSE.txt for further details.

   Revision history:
     Jan 2002: Created (Ralf W. Grosse-Kunstleve)

   *****************************************************
   THIS IS AN AUTOMATICALLY GENERATED FILE. DO NOT EDIT.
   *****************************************************

   Generated by:
     %s
 */""" % (sys.argv[0],)

arithmetic_unary_ops = ("-")
arithmetic_binary_ops = ("+", "-", "*", "/", "%")
arithmetic_in_place_binary_ops = ("+=", "-=", "*=", "/=", "%=")
logical_unary_ops = ("!")
logical_binary_ops = ("&&", "||")
boolean_ops = ("==", "!=", ">", "<", ">=", "<=")

reduction_functions_1arg = (
  "max_index", "min_index",
  "max", "min",
  "sum", "product",
  "mean",
)
reduction_functions_2arg = (
  "weighted_mean",
)

cmath_1arg = (
  'acos', 'cos', 'fmod', 'tan',
  'asin', 'cosh', 'tanh',
  'atan', 'exp', 'sin',
  'fabs', 'log', 'sinh',
  'ceil', 'floor', 'log10', 'sqrt',
)

cmath_2arg = (
  'fmod', 'pow', 'atan2',
)

cstdlib_1arg = (
  'abs',
)

class empty: pass

def line_breaks(indent, str, max_line_length = 79):
  maxlen = max_line_length - len(indent)
  extra_indent = ""
  lei = len(extra_indent)
  result = ""
  rest = str.strip()
  while (lei + len(rest) > maxlen):
    i = rest[:maxlen-lei].rindex(",")
    result += indent + extra_indent + rest[:i+1] + '\n'
    extra_indent = "  "
    lei = 2
    rest = rest[i+1:].strip()
  result += indent + extra_indent + rest
  return result

def format_list(indent, list):
  r = ""
  for line in list[:-1]:
    r += indent + line + "\n"
  return r + indent + list[-1]

def get_template_args(array_type_name):
  result = [["typename", "ElementType"]]
  if (array_type_name in ("tiny", "small")):
    result.append(["std::size_t", "N"])
  elif (array_type_name in ("ref", "versa")):
    result.append(["typename", "AccessorType"])
  return result

def get_numbered_template_args(array_type_name, n_params, equal_element_type):
  single = get_template_args(array_type_name)
  if (n_params == 1): return [single]
  result = []
  for i in xrange(1, n_params+1):
    if (equal_element_type):
      single_numbered = [single[0]]
    else:
      single_numbered = [[single[0][0], single[0][1]+str(i)]]
    if (array_type_name == "tiny"):
      single_numbered.append(single[1])
    else:
      for s in single[1:]:
        single_numbered.append([s[0], s[1]+str(i)])
    result.append(single_numbered)
  return result

def get_template_header_args(numbered_template_args):
  result = []
  for p in numbered_template_args:
    for d in p:
      if (not d in result): result.append(d)
  return result

def get_template_parameter_args(numbered_template_args):
  from string import join
  result = []
  for p in numbered_template_args:
    result.append(join([d[1] for d in p], ", "))
  return result

def get_template_header(numbered_template_args):
  from string import join
  ha = get_template_header_args(numbered_template_args)
  result = "template<" + join([join(x) for x in ha], ", ") + ">"
  return result

def get_template_parameters(array_type_name, template_parameter_args):
  result = []
  for p in template_parameter_args:
    result.append(array_type_name + "<" + p + ">")
  return result

def get_template_header_and_parameters(
  array_type_name, n_params, equal_element_type = 0
):
  result = empty()
  result.nta = get_numbered_template_args(
    array_type_name, n_params, equal_element_type)
  result.tpa = get_template_parameter_args(result.nta)
  result.header = get_template_header(result.nta)
  result.params = get_template_parameters(array_type_name, result.tpa)
  return result

def derive_return_array_type_simple(param):
  if (not param.startswith("small")): return param
  return param.replace("N1", "(N1<N2?N1:N2)")

def operator_decl_params(array_type_name, op_type, op_class, type_flags):
  if (type_flags != (1,1)):
    r = get_template_header_and_parameters(array_type_name, 1)
    r.params.insert(type_flags[0], "ElementType")
    if (op_type == "unary"):
      r.return_element_type = [
        "typename unary_operator_traits<",
        "  ElementType>::" + op_class]
    elif (op_class == "boolean"):
      r.return_element_type = [
        "typename binary_operator_traits<",
        "  ElementType, ElementType>::" + op_class]
    else:
      r.return_element_type = ["ElementType"]
  else:
    r = get_template_header_and_parameters(array_type_name, 2)
    r.return_element_type = [
      "typename binary_operator_traits<",
      "  ElementType1, ElementType2>::" + op_class]
  if (len(r.return_element_type) == 1):
    r.return_array_type = [array_type_name + "<" + r.return_element_type[0]]
  else:
    r.return_array_type = [
      array_type_name + "<",
      "  " + r.return_element_type[0],
      "    " + r.return_element_type[1]]
  if (len(r.nta[0]) == 2):
    if (r.nta[0][1][1] == "N1"):
      r.return_array_type[-1] += ", (N1<N2?N1:N2)"
    else:
      r.return_array_type[-1] += ", " + r.nta[0][1][1]
  r.return_array_type[-1] += ">"
  return r

def get_result_constructor_args(array_type_name, arg_name = "a"):
  if (array_type_name == "tiny"): return ""
  if (array_type_name == "versa"):
    return "(%s.accessor())" % (arg_name,)
  return "(%s.size())" % (arg_name,)

def binary_operator_algo_params(array_type_name, type_flags):
  r = empty()
  r.size_assert = ""
  r.loop_n = "N"
  r.result_constructor_args = ""
  if (array_type_name != "tiny"):
    if (type_flags == (1,1)):
      r.size_assert = """if (a1.size() != a2.size()) throw_range_error();
    """
    r.loop_n = "a%d.size()" % ((type_flags[0] + 1) % 2 + 1,)
    r.result_constructor_args = get_result_constructor_args(
      array_type_name, r.loop_n[:2])
  r.opsqbr = ["", ""]
  for i in xrange(2):
    if (type_flags[i]): r.opsqbr[i] = "[i]"
  return r

def elementwise_binary_op(
      array_type_name, op_class, op_symbol, type_flags, function_name):
  d = operator_decl_params(array_type_name, "binary", op_class, type_flags)
  a = binary_operator_algo_params(array_type_name, type_flags)
  print """%s
  inline
%s
  %s(
    const %s& a1,
    const %s& a2) {
%s
    result%s;
    %sfor(std::size_t i=0;i<%s;i++) result[i] = a1%s %s a2%s;
    return result;
  }
""" % (line_breaks("  ", d.header),
       format_list("  ", d.return_array_type),
       function_name, d.params[0], d.params[1],
       format_list("    ", d.return_array_type),
       a.result_constructor_args, a.size_assert, a.loop_n,
       a.opsqbr[0], op_symbol, a.opsqbr[1])

def elementwise_inplace_binary_op(
      array_type_name, op_class, op_symbol, type_flags):
  d = operator_decl_params(array_type_name, "binary", op_class, type_flags)
  a = binary_operator_algo_params(array_type_name, type_flags)
  print """%s
  inline
  %s&
  operator%s(
    %s& a1,
    const %s& a2) {
    %sfor(std::size_t i=0;i<%s;i++) a1[i] %s a2%s;
    return a1;
  }
""" % (line_breaks("  ", d.header),
       d.params[0],
       op_symbol, d.params[0], d.params[1],
       a.size_assert, a.loop_n,
       op_symbol, a.opsqbr[1])

def generate_elementwise_binary_op(
      array_type_name, op_class, op_symbol, function_name = None):
  if (function_name == None):
    function_name = "operator" + op_symbol
  for type_flags in ((1,1), (1,0), (0,1)):
    elementwise_binary_op(
      array_type_name, op_class, op_symbol, type_flags, function_name)

def generate_elementwise_inplace_binary_op(
      array_type_name, op_class, op_symbol):
  for type_flags in ((1,1), (1,0)):
    elementwise_inplace_binary_op(
      array_type_name, op_class, op_symbol, type_flags)

def reducing_boolean_op(array_type_name, op_symbol, type_flags):
  d = operator_decl_params(array_type_name, "binary", "boolean", type_flags)
  a = binary_operator_algo_params(array_type_name, type_flags)
  truth_test_type = "ElementType"
  if (type_flags == (1,1)):
    truth_test_type = "ElementType1"
  if (op_symbol == "=="):
    if (a.size_assert != ""):
      a.size_assert = """if (a1.size() != a2.size()) return %s() != %s();
    """ % (truth_test_type, truth_test_type)
    tests = (
"""      if (a1%s != a2%s) return %s() != %s();"""
    % (a.opsqbr[0], a.opsqbr[1], truth_test_type, truth_test_type))
    final_op = "=="
  elif (op_symbol == "!="):
    if (a.size_assert != ""):
      a.size_assert = """if (a1.size() != a2.size()) return %s() == %s();
    """ % (truth_test_type, truth_test_type)
    tests = (
"""      if (a1%s != a2%s) return %s() == %s();"""
    % (a.opsqbr[0], a.opsqbr[1], truth_test_type, truth_test_type))
    final_op = "!="
  elif (op_symbol in ("<", ">")):
    tests = (
"""      if (a1%s %s a2%s) return %s() == %s();
      if (a2%s %s a1%s) return %s() != %s();"""
    % (a.opsqbr[0], op_symbol, a.opsqbr[1], truth_test_type, truth_test_type,
       a.opsqbr[1], op_symbol, a.opsqbr[0], truth_test_type, truth_test_type))
    final_op = "!="
  elif (op_symbol in ("<=", ">=")):
    tests = (
"""      if (!(a1%s %s a2%s)) return %s() != %s();"""
    % (a.opsqbr[0], op_symbol, a.opsqbr[1], truth_test_type, truth_test_type))
    final_op = "=="
  print """%s
  inline
%s
  operator%s(
    const %s& a1,
    const %s& a2) {
    %sfor(std::size_t i=0;i<%s;i++) {
%s
    }
    return %s() %s %s();
  }
""" % (line_breaks("  ", d.header),
       format_list("  ", d.return_element_type),
       op_symbol, d.params[0], d.params[1],
       a.size_assert, a.loop_n, tests,
       truth_test_type, final_op, truth_test_type)

def generate_reducing_boolean_op(array_type_name, op_symbol):
  for type_flags in ((1,1), (1,0), (0,1)):
    reducing_boolean_op(array_type_name, op_symbol, type_flags)

def generate_unary_ops(array_type_name):
  result_constructor_args = get_result_constructor_args(array_type_name)
  for op_class, op_symbol in (("arithmetic", "-"),
                              ("logical", "!")):
    d = operator_decl_params(array_type_name, "unary", op_class, (1,0))
    print """%s
  inline
%s
  operator%s(const %s& a) {
%s
    result%s;
    for(std::size_t i=0;i<a.size();i++) result[i] = %sa[i];
    return result;
  }
""" % (line_breaks("  ", d.header),
       format_list("  ", d.return_array_type),
       op_symbol, d.params[0],
       format_list("    ", d.return_array_type),
       result_constructor_args,
       op_symbol)

def generate_1arg_reductions(array_type_name):
  hp = get_template_header_and_parameters(array_type_name, 1)
  for function_name in reduction_functions_1arg:
    print """%s
  inline
  ElementType
  %s(const %s& a) {
    return %s(a.const_ref());
  }
""" % (line_breaks("  ", hp.header),
       function_name, hp.params[0],
       function_name)

def generate_2arg_reductions(array_type_name):
  hp = get_template_header_and_parameters(array_type_name, 2)
  for function_name in reduction_functions_2arg:
    print """%s
  inline
  ElementType1
  %s(
    const %s& a1,
    const %s& a2) {
    return %s(a1.const_ref(), a2.const_ref());
  }
""" % (line_breaks("  ", hp.header),
       function_name, hp.params[0], hp.params[1],
       function_name)

def generate_1arg_element_wise(array_type_name, prefix, function_names):
  hp = get_template_header_and_parameters(array_type_name, 1)
  rt = derive_return_array_type_simple(hp.params[0])
  result_constructor_args = get_result_constructor_args(array_type_name)
  for function_name in function_names:
    print """%s
  inline
  %s
  %s(const %s& a) {
    %s result%s;
    for(std::size_t i=0;i<a.size();i++) result[i] = %s(a[i]);
    return result;
  }
""" % (line_breaks("  ", hp.header), rt,
       function_name, hp.params[0],
       rt, result_constructor_args,
       prefix + function_name)

def generate_2arg_element_wise(
  array_type_name, prefix, function_names,
  equal_element_type = 0,
  addl_args = ["", ""]
):
  hp = get_template_header_and_parameters(
    array_type_name, 2, equal_element_type)
  rt = derive_return_array_type_simple(hp.params[0])
  result_constructor_args = get_result_constructor_args(array_type_name, "a1")
  for function_name in function_names:
    print """%s
  inline
  %s
  %s(
    const %s& a1,
    const %s& a2%s) {
    %s result%s;
    for(std::size_t i=0;i<a1.size();i++) {
      result[i] = %s(a1[i], a2[i]%s);
    }
    return result;
  }
""" % (line_breaks("  ", hp.header), rt,
       function_name, hp.params[0], hp.params[1], addl_args[0],
       rt, result_constructor_args,
       prefix + function_name, addl_args[1])

def one_type(array_type_name):
  f = open("%s_algebra.h" % (array_type_name,), "w")
  sys.stdout = f
  write_copyright()
  print """
#ifndef CCTBX_ARRAY_FAMILY_%s_ALGEBRA_H
#define CCTBX_ARRAY_FAMILY_%s_ALGEBRA_H
""" % ((array_type_name.upper(),) * 2)
  if (array_type_name != "ref"):
    print """#include <cmath>
#include <cstdlib>
#include <cctbx/array_family/misc_functions.h>
#include <cctbx/array_family/operator_traits_builtin.h>"""
  print """#include <cctbx/array_family/reductions.h>

namespace cctbx { namespace af {
"""

  if (array_type_name != "ref"):
    generate_unary_ops(array_type_name)
    for op_symbol in arithmetic_binary_ops:
      generate_elementwise_binary_op(
        array_type_name, "arithmetic", op_symbol)
      generate_elementwise_inplace_binary_op(
        array_type_name, "arithmetic", op_symbol + "=")
    for op_symbol in logical_binary_ops:
      generate_elementwise_binary_op(
        array_type_name, "logical", op_symbol)
    for op_symbol, function_name in (
      ("==", "equal_to"),
      ("!=", "not_equal_to"),
      (">", "greater"),
      ("<", "less"),
      (">=", "greater_equal"),
      ("<=", "less_equal")):
      generate_elementwise_binary_op(
        array_type_name, "boolean", op_symbol, function_name)
    for op_symbol in boolean_ops:
      generate_reducing_boolean_op(array_type_name, op_symbol)
    generate_1arg_element_wise(array_type_name,
      "std::", cmath_1arg + cstdlib_1arg)
    generate_2arg_element_wise(array_type_name,
      "std::", cmath_2arg)
    generate_2arg_element_wise(array_type_name,
      "", ["approx_equal_scaled"],
      1,
      [", const ElementType& scaled_tolerance",
       ", scaled_tolerance"])
    generate_2arg_element_wise(array_type_name,
      "", ["approx_equal_unscaled"],
      1,
      [", const ElementType& tolerance",
       ", tolerance"])
  generate_1arg_reductions(array_type_name)
  generate_2arg_reductions(array_type_name)

  print """}} // namespace cctbx::af

#endif // CCTBX_ARRAY_FAMILY_%s_ALGEBRA_H""" % (array_type_name.upper(),)
  sys.stdout = sys.__stdout__
  f.close()

def run():
  for array_type_name in ("ref", "tiny", "small", "shared", "versa"):
    one_type(array_type_name)

if (__name__ == "__main__"):
  run()
