Import("env_base", "env_etc")
env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
)
env_etc.include_registry.append(
  env=env,
  paths=env_etc.scitbx_common_includes)
envlm = env.Copy(
  LIBS=env_etc.libm
)
envlm.Program(target="tst_lbfgs", source="tst_lbfgs.cpp")

if (not env_etc.no_boost_python):
  Import("env_scitbx_boost_python_ext")
  env_scitbx_boost_python_ext.SharedLibrary(
    target="#lib/scitbx_lbfgs_ext",
    source=["ext.cpp"])
