Import("env_iotbx_boost_python_ext")
env = env_iotbx_boost_python_ext.Copy()
env.Prepend(LIBS=["iotbx",])
pyd = env.SharedLibrary(target="xplor", source=[
  "xplormodule.cpp",
])
env.Install("#libtbx/iotbx_boost", pyd)
