Import("env_etc", "env_scitbx_boost_python_ext")
env = env_scitbx_boost_python_ext.Clone()
env_etc.enable_more_warnings(env=env)
env.SharedLibrary(
  target="#lib/scitbx_rigid_body_ext",
  source=["ext.cpp"])
