Import("env_etc", "env_scitbx_boost_python_ext")

env_scitbx_boost_python_ext.SharedLibrary(target="regression_test_ext", source=[
  "regression_test_ext.cpp",
])

env_scitbx_boost_python_ext.Command(
  "#libtbx/scitbx_boost/array_family/__init__.py",
  "#libtbx/libtbx/touch_init.py", env_etc.touch_init)

env_scitbx_boost_python_ext.SharedLibrary(
  target="#libtbx/scitbx_boost/array_family/flex_scitbx_ext",
  source=[
  "flex_scitbx_ext.cpp",
  "flex_grid.cpp",
  "flex_bool.cpp",
  "flex_size_t.cpp",
  "flex_int.cpp",
  "flex_int_2.cpp",
  "flex_long.cpp",
  "flex_long_2.cpp",
  "flex_float.cpp",
  "flex_float_2.cpp",
  "flex_double.cpp",
  "flex_double_2.cpp",
  "flex_complex_double.cpp",
  "flex_complex_double_2.cpp",
  "flex_std_string.cpp",
  "flex_sort.cpp",
  "flex_histogram.cpp",
  "flex_mean_and_variance.cpp",
])
