#!/usr/bin/python

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))
import install_cctbx_base

if (__name__ == "__main__") :
  install_cctbx_base.installer(args=sys.argv, log=sys.stdout)
