Import("env_cctbx_boost_python_ext")
env_bpl = env_cctbx_boost_python_ext.Copy()
env_bpl.Prepend(LIBS=["cctbx"])
env_bpl.SharedLibrary(
  target="#lib/cctbx_adp_restraints_ext",
  source=[
    "adp_restraints_ext.cpp",
    "rigid_bond_bpl.cpp",
    "rigid_bond.cpp",
    "adp_similarity_bpl.cpp",
    "adp_similarity.cpp",
    "isotropic_adp_bpl.cpp",
    "isotropic_adp.cpp"])
