Import("env_iotbx_boost_python_ext")
env = env_iotbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
for ext in ("dtrek", "scalepack"):
  env.SharedLibrary(
    target="#lib/iotbx_"+ext+"_ext",
    source=ext+"_ext.cpp")
