Import("env_cctbx_boost_python_ext")

env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(
  target="#lib/cctbx_array_family_flex_ext",
  source=[
  "flex_ext.cpp",
  "flex_hendrickson_lattman.cpp",
  "flex_miller_index.cpp",
  "flex_xray_scatterer.cpp",
])
