Import("env_cctbx_boost_python_ext")

env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(
  target="#lib/cctbx_array_family_flex_ext",
  source=[
  "flex_ext.cpp",
  "flex_hendrickson_lattman.cpp",
  "flex_miller_index.cpp",
  "flex_sym_mat3_double.cpp",
  "flex_tiny_size_t_2.cpp",
  "flex_xray_scatterer.cpp",
  "flex_evaluated_axis.cpp",
])
