Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#lib/cctbx_miller_ext", source=[
  "miller_ext.cpp",
  "asu.cpp",
  "bins.cpp",
  "change_basis.cpp",
  "expand_to_p1.cpp",
  "index_generator.cpp",
  "index_span.cpp",
  "match_bijvoet_mates.cpp",
  "match_indices.cpp",
  "match_multi_indices.cpp",
  "merge_equivalents.cpp",
  "phase_integrator.cpp",
  "phase_transfer.cpp",
  "sym_equiv.cpp",
  "f_calc_map.cpp",
  "lookup_utils.cpp",
  "amplitude_normalisation.cpp",
  "randomize_amplitude_and_phase.cpp",
  "slices.cpp",
])
