Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#libtbx/cctbx_boost/miller_ext", source=[
  "miller_ext.cpp",
  "asu.cpp",
  "bins.cpp",
  "expand_to_p1.cpp",
  "index_generator.cpp",
  "index_span.cpp",
  "match_bijvoet_mates.cpp",
  "match_indices.cpp",
  "merge_equivalents.cpp",
  "phase_transfer.cpp",
  "sym_equiv.cpp",
])
