Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
pyd = env.SharedLibrary(target="miller_ext", source=[
  "miller_ext.cpp",
  "asu.cpp",
  "bins.cpp",
  "expand_to_p1.cpp",
  "index_generator.cpp",
  "index_span.cpp",
  "match_bijvoet_mates.cpp",
  "match_indices.cpp",
  "sym_equiv.cpp",
])
env.Install("#libtbx/cctbx_boost", pyd)
