Import("env_base", "env_etc")
env = env_base.Clone()
env_etc.enable_more_warnings(env=env)
env_etc.include_registry.append(
  env=env,
  paths=["."] + env_etc.scitbx_common_includes)
envlm = env.Clone(
  LIBS=env_etc.libm
)
envlm.Program(target="tst_base_256", source="tst_base_256.cpp")
