Import("env_base", "env_etc")
env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
  CPPPATH=["."] + env_etc.scitbx_common_includes,
)
envlm = env.Copy(
  LIBS=env_etc.libm
)
envlm.Program(target="tst_base_256", source="tst_base_256.cpp")
