Import("env_base", "env_etc")

env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
  SHCXXFLAGS=env_etc.cxxflags_base,
  SHLINKFLAGS=env_etc.shlinkflags,
  CPPPATH=env_etc.scitbx_common_includes + [env_etc.python_include],
)
env.Append(CXXFLAGS=env_etc.cxxflags_bpl_defines_base)
env.Append(SHCXXFLAGS=env_etc.cxxflags_bpl_defines_base)
env.Append(LIBPATH=["#libtbx"])
env.Append(LIBS=["boost_python"])

lib_scitbx_boost_python_sources = [
  "#scitbx/boost_python/utils.cpp",
  "#scitbx/boost_python/slice.cpp",
  "#scitbx/array_family/boost_python/utils.cpp",
]
if (env_etc.static_libraries): builder = env.StaticLibrary
else:                          builder = env.SharedLibrary
builder(
  target="#libtbx/scitbx_boost_python",
  source=lib_scitbx_boost_python_sources)

Import("env_scitbx_boost_python_ext")
env_scitbx_boost_python_ext.SharedLibrary(
  target="#libtbx/scitbx_boost/rational_ext",
  source="rational_ext.cpp",
)
