Import("env_base", "env_etc")

env = env_base.Copy(
  CXXFLAGS=env_etc.cxxflags_base,
  SHCXXFLAGS=env_etc.cxxflags_base,
  SHLINKFLAGS=env_etc.shlinkflags,
  CPPPATH=env_etc.scitbx_common_includes + [env_etc.python_include],
)
env.Append(CXXFLAGS=env_etc.cxxflags_bpl_defines_base)
env.Append(SHCXXFLAGS=env_etc.cxxflags_bpl_defines_base)

scitbx_boost_python_sources = [
  "#/scitbx/boost_python/utils.cpp",
  "#/scitbx/array_family/boost_python/utils.cpp",
  "#/scitbx/array_family/boost_python/tiny_conversions.cpp",
  "#/scitbx/array_family/boost_python/small_conversions.cpp",
]
if (env_etc.is_win32): builder = env.StaticLibrary
else:                  builder = env.SharedLibrary
lib_scitbx_boost_python = builder(
    target="scitbx_boost_python",
    source=scitbx_boost_python_sources)
env.Install("#/libtbx", lib_scitbx_boost_python)
