Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Copy()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#libtbx/cctbx_translation_search_ext", source=[
  "translation_search_ext.cpp",
  "fast_nv1995.cpp",
  "fast_terms.cpp",
  "symmetry_flags.cpp",
])
