Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx", "omptbx"])
env.SharedLibrary(target="#lib/cctbx_translation_search_ext", source=[
  "translation_search_ext.cpp",
  "fast_nv1995.cpp",
  "fast_terms.cpp",
  "symmetry_flags.cpp",
])
