Import("env_etc")
if (not env_etc.no_boost_python):
  Import("env_cctbx_boost_python_ext")
  env_bpl = env_cctbx_boost_python_ext.Clone()
  env_etc.include_registry.append(
    env=env_bpl,
    paths=env_etc.mmtbx_common_includes)
  env_bpl.Prepend(LIBS=["cctbx"])
  env_bpl.SharedLibrary(
    target="#lib/mmtbx_ncs_restraints_ext",
    source=["restraints_ext.cpp"])
