import libtbx.load_env
import os
Import("env_etc")

env_etc.mmtbx_dist = libtbx.env.dist_path("mmtbx")
env_etc.mmtbx_include = os.path.dirname(env_etc.mmtbx_dist)

env_etc.mmtbx_common_includes = [
  env_etc.libtbx_include,
  env_etc.mmtbx_include,
  env_etc.cctbx_include,
  env_etc.scitbx_include,
  env_etc.boost_include,
]

if not libtbx.env.module_is_installed("mmtbx"):
  SConscript("alignment/SConscript")
  SConscript("masks/SConscript")
  SConscript("ncs/SConscript")
  SConscript("max_lik/SConscript")
  SConscript("dynamics/SConscript")
  SConscript("bulk_solvent/SConscript")
  SConscript("tls/SConscript")
  SConscript("scaling/SConscript")
  SConscript("f_model/SConscript")
  SConscript("utils/SConscript")
  SConscript("rsr/SConscript")
  SConscript("geometry_restraints/SConscript")
  SConscript("secondary_structure/SConscript")
  SConscript("den/SConscript")
  SConscript("geometry/SConscript")
  SConscript("rotamer/SConscript")
  SConscript("validation/SConscript")
  SConscript("building/SConscript")
  SConscript("hydrogens/SConscript")
  SConscript("pair_interaction/SConscript")
  SConscript("probe/SConscript")
  SConscript("reduce/SConscript")
