Import("env_etc")
if (not env_etc.no_boost_python):
  Import("env_iotbx_boost_python_ext")
  env = env_iotbx_boost_python_ext.Copy()
  env.Append(LIBPATH=["#lib"])
  env.Prepend(LIBS=["cctbx", "scitbx_boost_python"])
  env.SharedLibrary(
    target="#lib/iotbx_pdb_ext",
    source=[
      "ext.cpp",
      "hierarchy_bpl.cpp",
      "input_bpl.cpp",
      "xray_structure_bpl.cpp"])
