Import("env_scitbx_boost_python_ext", "env_etc")

for stl_type in ["map", "set", "vector"]:
  env = env_scitbx_boost_python_ext.Clone()
  env_etc.enable_more_warnings(env=env)
  env.SharedLibrary(
    target="#lib/scitbx_stl_%s_ext" % stl_type,
    source=[
    "%s_ext.cpp" % stl_type,
  ])
