Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(
  target="#lib/cctbx_uctbx_ext",
  source=["uctbx_ext.cpp", "fast_minimum_reduction.cpp"])
