Import("env_rstbx_boost_python_ext", "env_etc")

env = env_rstbx_boost_python_ext.Clone()
env_etc.enable_more_warnings(env=env)

env.SharedLibrary(
  target="#lib/rstbx_bpcx_detector_model_ext",
  source=[
    "detector_model/detector_model_ext.cpp",
    "detector_model/sensor.cpp",
  ]
)
