Import("env_clipper_boost_python_ext")
env = env_clipper_boost_python_ext.Copy()
env.Prepend(LIBS=["clipper", "cctbx"])
env.SharedLibrary(
  target="#libtbx/clipper_ext",
  source=[
    "clipper_ext.cpp",
    "sigmaa_bpl.cpp",
    "../../clipper/clipper/contrib/sfweight.cpp",
    "../../clipper/clipper/cctbx/clipper_cctbx.cpp"])
