# Dockerfile for adding dependencies to base ubuntu:24.04 image

FROM ubuntu:24.04

RUN export DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get install -y \
         build-essential \
         curl \
         firefox \
         git \
         libgl1-mesa-dev \
         libglu1-mesa-dev \
         libxcomposite-dev \
         libxss1 \
         locales \
         pciutils \
         rsync \
         sudo \
         unzip \
         wget \
    && locale-gen en_US.UTF-8 \
    && update-locale \
    && rm -fr /var/lib/apt/lists/*
