Import("env_cctbx_boost_python_ext")
env = env_cctbx_boost_python_ext.Clone()
env.Prepend(LIBS=["cctbx"])
env.SharedLibrary(target="#lib/cctbx_crystal_ext", source=[
  "crystal_ext.cpp",
  "asu_clusters_bpl.cpp",
  "close_packing_bpl.cpp",
  "coordination_sequences_bpl.cpp",
  "direct_space_asu_bpl.cpp",
  "incremental_pairs_bpl.cpp",
  "neighbors_bpl.cpp",
  "pair_tables_bpl.cpp",
  "site_cluster_analysis_bpl.cpp",
  "symmetry_bpl.cpp",
])
