Import("env_rstbx_boost_python_ext", "env_etc")

env = env_rstbx_boost_python_ext.Clone()
env_etc.enable_more_warnings(env=env)
env.SharedLibrary(
  target="#lib/rstbx_diffraction_fastbragg_ext",
  source=[
    "fastbragg_ext.cpp",
    "fastbragg.cpp",
  ]
)
