name: test
on:
  workflow_dispatch:
  push:

jobs:
  test_pr_1044:

    name: Testing PR 1044
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: cctbx_project

      - name: Run Docker
        run: |
          cd cctbx_project/fable/docker
          docker buildx build -t fable-dock .

      - name: Run example
        run: docker run -i -w $(pwd) --volume=$(pwd):$(pwd):rw -t fable-dock --example
