# LIBTBX_SET_DISPATCHER_NAME cctbx.wxpython
# LIBTBX_PRE_DISPATCHER_INCLUDE_SH PHENIX_GUI_ENVIRONMENT=1
# LIBTBX_PRE_DISPATCHER_INCLUDE_SH export PHENIX_GUI_ENVIRONMENT
# LIBTBX_START_PYTHON
from __future__ import absolute_import, division, print_function
